spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: company-ms
              uri: lb://COMPANY-MS
              predicates:
                - "Path=/companies/**"
            - id: job-ms
              uri: lb://JOB-MS
              predicates:
                - "Path=/jobs/**"
            - id: review-ms
              uri: http://localhost:8083
              predicates:
                - "Path=/reviews/**"

server:
  port: 8080

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: "http://localhost:8761/eureka/"
