apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-ms
  template:
    metadata:
      labels:
        app: job-ms
    spec:
      containers:
        - name: job-ms
          image: first-job-ms-job-ms:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_HOST
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://$(POSTGRES_HOST):5432/job-ms
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ZIPKIN_ENDPOINT
            - name: EUREKA_DEFAULT_ZONE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: EUREKA_DEFAULT_ZONE
          args:
            - "--eureka.client.service-url.defaultZone=$(EUREKA_DEFAULT_ZONE)"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 6
