spring:
  application:
    name: review-ms
  datasource:
    url: jdbc:postgresql://localhost:5432/review-ms
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    anyProp: "anyValue"

server:
  port: 8083


