spring:
  application:
    name: job-ms
  datasource:
    url: jdbc:postgresql://localhost:5432/job-ms
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
#    export:
#      zipkin:
#        endpoint: "http://localhost:9411/zipkin/api/v2/spans"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    shutdown:
      access:
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    anyProp: "anyValue"


server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: "http://localhost:8761/eureka/"

resilience4j:
  ratelimiter:
    instances:
      getAllJobsRateLimiter:
        timeout-duration: 1s
        limit-for-period: 1
        limit-refresh-period: 10S
  retry:
    instances:
      reviewRetry:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - feign.FeignException.ServiceUnavailable # Clean nested class notation
          - feign.RetryableException
          - feign.FeignException.GatewayTimeout
          - feign.FeignException.BadGateway
          - feign.FeignException.TooManyRequests
          - java.io.IOException
          - java.net.ConnectException
        ignore-exceptions:
          - feign.FeignException.BadRequest
          - feign.FeignException.Unauthorized
          - feign.FeignException.Forbidden
          - feign.FeignException.NotFound
          - feign.FeignException.MethodNotAllowed
          - feign.FeignException.Conflict
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
    instances:
      companyBreaker:
        base-config: default
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count_based


